# Generated by Django 4.2.3 on 2023-07-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0003_alter_orders_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantitity',
            field=models.IntegerField(default=1),
        ),
    ]
