# Generated by Django 4.2.3 on 2023-07-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0004_cartitem_quantitity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantitity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='quantitity',
            new_name='quantity',
        ),
    ]
