# Generated by Django 4.2.3 on 2023-07-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0005_rename_quantitity_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.TextField(default=''),
        ),
    ]
