# Generated by Django 4.2.3 on 2023-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0006_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_discount',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_price',
            field=models.TextField(),
        ),
    ]
