# Generated by Django 4.2.3 on 2023-07-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0008_orders_date_orders_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date',
            new_name='orderdate',
        ),
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireapp.orders')),
            ],
        ),
    ]
