# Generated by Django 4.2.3 on 2023-07-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0009_rename_date_orders_orderdate_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderdate',
            field=models.DateField(),
        ),
    ]
