# Generated by Django 4.2.3 on 2023-07-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0010_alter_orders_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered',
            name='ordered_date',
            field=models.DateTimeField(),
        ),
    ]
