# Generated by Django 4.2.3 on 2023-07-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0011_alter_delivered_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivered',
            name='ordered_date',
        ),
    ]
